nome = str(input("Digite o seu nome ")).strip()
print(nome.upper())
print(nome.lower())
print(len(nome) - nome.count(' '))
print(nome.find(' '))
separa = nome.split()
print("O primeiro nome é {}".format(separa[0], len(separa[0])))
